### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/tap-csv-folder#8]
```[tasklist]
### Tasks
- [x] Set up trusted publisher on PyPI: Created in the MeltanoLabs PyPI account
- [x] Set up `pypi` environment in this GitHub repo, with some permissions
- [x] Use VCS versioning: https://github.com/meltano/tap-csv-folder/pull/9
- [x] Add a build + release workflow: https://github.com/meltano/tap-csv-folder/tree/main/.github/workflows/build.yml
- [x] Publish first alpha: https://pypi.org/project/tap-csv-folder/0.0.1a1/
```
